//
//  DutchPayViewModel.swift
//  WorkOutTimer
//
//  Created by 김태훈 on 7/22/25.
//
import SwiftUI
import Combine

@MainActor
class DutchPayViewModel: ObservableObject {
    
    // MARK: - Published Properties
    @Published var people: [Person] = []
    @Published var totalAmount: String = ""
    @Published var numberOfPeople: String = ""
    @Published var showingAlert = false
    @Published var alertMessage = ""
    
    // MARK: - Constants
    private struct Constants {
        static let maxPeople = 10
        static let minPeople = 1
    }
    
    // MARK: - Computed Properties
    var canAddPerson: Bool {
        people.count < Constants.maxPeople
    }
    
    var totalAmountDouble: Double {
        Double(totalAmount) ?? 0
    }
    
    var numberOfPeopleInt: Int {
        max(Constants.minPeople, min(Constants.maxPeople, Int(numberOfPeople) ?? 2))
    }
    
    var dutchPayResult: DutchPayResult? {
        guard totalAmountDouble > 0, !people.isEmpty else { return nil }
        
        let totalAdditionalAmount = people.reduce(0) { $0 + $1.additionalAmount }
        let remainingAmount = totalAmountDouble - totalAdditionalAmount
        let baseAmountPerPerson = remainingAmount / Double(people.count)
        
        guard baseAmountPerPerson >= 0 else { return nil }
        
        let payments = people.map { person in
            PersonPayment(
                person: person,
                totalPayment: baseAmountPerPerson + person.additionalAmount,
                basePayment: baseAmountPerPerson,
                additionalPayment: person.additionalAmount
            )
        }
        
        return DutchPayResult(
            totalAmount: totalAmountDouble,
            baseAmountPerPerson: baseAmountPerPerson,
            people: payments
        )
    }
    
    var isCalculationValid: Bool {
        guard let result = dutchPayResult else { return false }
        return result.baseAmountPerPerson >= 0
    }
    
    // MARK: - Initialization
    init() {
        // 빈 상태로 시작 - 필요시 사용자가 인원 수를 입력하고 확인 버튼을 누르거나 + 버튼으로 추가
        // setupInitialPeople() - 주석 처리하여 빈 상태로 시작
    }
    
    // MARK: - Public Methods
    func addPerson() {
        guard canAddPerson else {
            showAlert(message: "최대 \(Constants.maxPeople)명까지만 추가할 수 있습니다.")
            return
        }
        
        let newPerson = Person(name: "") // 빈 이름으로 생성
        people.append(newPerson)
        numberOfPeople = String(people.count) // 인원 수 필드 업데이트
    }
    
    func removePerson(at index: Int) {
        guard people.indices.contains(index) else { return }
        guard people.count > 1 else {
            showAlert(message: "최소 1명은 있어야 합니다.")
            return
        }
        
        people.remove(at: index)
        numberOfPeople = String(people.count) // 인원 수 필드 업데이트
        
        // 기본 이름 패턴을 사용하는 경우 이름 재정렬
        updateAutoNamesIfNeeded()
    }
    
    func updatePersonName(at index: Int, name: String) {
        guard people.indices.contains(index) else { return }
        people[index].name = name // 빈 이름도 그대로 유지
    }
    
    func updatePersonAdditionalAmount(at index: Int, amount: String) {
        guard people.indices.contains(index) else { return }
        people[index].additionalAmount = Double(amount) ?? 0
    }
    
    func updateNumberOfPeople(_ count: String) {
        numberOfPeople = count
    }
    
    func applyNumberOfPeople() {
        let targetCount = numberOfPeopleInt
        
        // 현재 인원수와 목표 인원수 비교하여 조정
        if people.count < targetCount {
            // 인원 추가 - 빈 이름으로 생성
            while people.count < targetCount && people.count < Constants.maxPeople {
                let newPerson = Person(name: "") // 빈 이름으로 생성
                people.append(newPerson)
            }
        } else if people.count > targetCount {
            // 인원 감소
            while people.count > targetCount && people.count > Constants.minPeople {
                people.removeLast()
            }
        }
    }
    
    func resetCalculation() {
        totalAmount = ""
        numberOfPeople = "" // 빈 값으로 초기화
        people.removeAll() // 참여자 목록 완전 초기화
    }
    
    // 자동 이름 채우기 기능
    func fillAutoNames() {
        for index in people.indices {
            people[index].name = getAutoGeneratedName(for: index)
        }
    }
    
    // MARK: - Private Methods
    private func setupInitialPeople() {
        let initialCount = numberOfPeopleInt
        for i in 0..<initialCount {
            let person = Person(name: getAutoGeneratedName(for: i))
            people.append(person)
        }
    }
    
    // 참여자1, 참여자2 형식으로 자동 이름 생성
    private func getAutoGeneratedName(for index: Int) -> String {
        return "참여자\(index + 1)"
    }
    
    // 자동 생성된 이름인지 확인
    private func isAutoGeneratedName(_ name: String) -> Bool {
        return name.hasPrefix("참여자")
    }
    
    // 필요시 자동 이름 재정렬
    private func updateAutoNamesIfNeeded() {
        for (index, person) in people.enumerated() {
            // 기본 이름 패턴을 사용하는 경우에만 재정렬
            if isAutoGeneratedName(person.name) {
                people[index].name = getAutoGeneratedName(for: index)
            }
        }
    }
    
    private func showAlert(message: String) {
        alertMessage = message
        showingAlert = true
    }
}
